### ISSUE TITLE
Sassを理解する

### ISSUE THREAD

**Issue by bossato** [bossato/sass#1]
### ■目的

CSSメタ言語「Sass」を利用する際に必要な基礎知識を習得します。
### ■課題

下記用語について調査し、issueに記述してください。
- Sass
- mixin
- extend
- import
- partial
- Sassで使える記法(2つ)とそれぞれの特徴
- Sass特殊文字
  - `&`
  - `%`
  - `#{}`
- Sassで使える制御構文(4つ)

**Comment by bossato** [comment]
- Sass
  - CSSの拡張メタ言語の一種
  - インデントや変数などプログラムと同様の書き方が可能
  - コンパイルしてCSSファイルを生成
- mixin
  - 再利用可能なスタイルを生成する機能
  - mixinで再利用するスタイルを記述した名前を定義し、適用したいセレクタに対し読込を行う
- extend
  - スタイルを定義したセレクタを継承する
  - mixinとの違いは主に以下
    - 引数を渡せない
    - 複数のセレクターに対し適用した場合、コンパイル後グルーピングされる
- import
  - CSSのimport同様、ファイルの読み込みを行う機能
  - コンパイルしても1つのCSSファイルが生成されるのでリクエストが減らせる
- partial
  - 分割したSCSSファイルの事
  - アンダーバーから始まるファイル名にする必要がある
  - コンパイルしてもCSSファイルが生成されない
  - ページ単位、人単位などのルールでファイル分割する事で管理がしやすくなる
- Sassで使える記法(2つ)とそれぞれの特徴
  - ネスト
    - 親セレクタ、子セレクタををネストする事でコンパイル後のCSSでは各セレクタに分割してレンダリングされる
    
    ```
    // sass
    #content [
      h1 { font-size: 120%; }
      h2 { font-size: 110%; }
    }
    ```
    
    ```
    // css
    #content h1 [
      font-size: 120%;
    }
    #content h2 [
      font-size: 110%;
    }
    ```
  - 変数
    - 名前と値を定義し、任意のセレクタで呼び出すことでその値が適用される
    
    ```
    // sass
    $font_size: 120%;
    
    #content [
      h1 { font-size: $font_size; }
    }
    ```
    
    ```
    // css
    #content h1 [
      font-size: 120%;
    }
    ```
- Sass特殊文字
  - `&`
    - 親セレクタに置換
  - `%`
    - プレースホルダ―
    - `extend`同様、スタイルの継承が可能
    - プレースホルダ―で定義したセレクタ、スタイルは出力されない
  - `#{}`
    - 補完
    - 変数の値をセレクタやプロパティに適用する事が可能
    
    ```
    // sass
    $name: content;
    $attr: size;
    ##{$name} [
      h1 { font-#{$attr}: 10px; }
    }
    ```
    
    ```
    // css
    #content [
      h1 { font-size: 10px; }
    }
    ```
- Sassで使える制御構文(4つ)
  - `@if`
    - 条件分岐
    - `@else if`や`@else1も可能
    
    ```
    @if 条件1 {
      ・
      ・
    } @else if 条件2 {
      ・
      ・
    } @else {
      ・
      ・
    }
    ```
  - `@for`
    - 1ずつカウントアップする繰り返し
    
    ```
    @for $i from 開始値 to 終了値 {
      ・
      ・
    }
    ```
    - 終了値の指定方法
      - `to`:終了値の1つ前まで
      - `through`:終了値前まで
  - `@while`
    - 条件を満たすまで繰り返す処理
    
    ```
    @while 条件 {
      ・
      ・
    }
    ```
  - `@each`
    - 指定したリストを順番に処理
    
    ```
    @each 変数名 in リスト {
      ・
      ・
    }
    ```

**Comment by bossato** [comment]
## ■追加課題

Sassは2種類の文法で記述することが出来ます。
下記の文法の特徴について調べてみましょう！
- Sass
- Sassy CSS(SCSS)

**Comment by bossato** [comment]
- Sass
  - 課題にある変数、ネスト、制御構文などプログラムに近い形で記述できる
  - CSSをより簡略化した文法(`;`や`{}`の省略など)
- Sassy CSS(SCSS)
  - Sass3.0以降よりサポートされている文法
  - 基本的な機能はSassと同様
  - Sassに比べ、CSSに近い形で記述出来る

**Comment by fr-itaya** [comment]
確認しました、バッチリです！:star::star::star:
この後の課題でどちらの文法をお使いになるかはお任せします！
(Hamlに慣れている人はSass文法の方がとっつき易い等、技術的バックグラウンドによってどちらが書きやすいか変わると思うので)

**Comment by bossato** [comment]
### 思った事
- Sassを使うメリット的な所も課題に入れると、なぜSassを使った方がよいか納得できそう
- `mixin`や`extend`などの記述方に関してはコード書く課題絡めて調査、書いてもらった方が分かり易いかも(サーバサイドの課題でも言える
  - 機能単位や構文単位で課題を細分化してもいいかもしれない

**Comment by fr-itaya** [comment]
> - Sassを使うメリット的な所も課題に入れると、なぜSassを使った方がよいか納得できそう

確かに。調査課題に追加させて頂きます！

> - `mixin`や`extend`などの記述方法に関してはコード書く課題絡めて調査、書いてもらった方が分かり易いかも

コード込みとなると、「mixin、extendを使ってみる」のような、別issueにするのもいいかもしれません。また考えます。

> 課題を細分化

issue3で頂いたフィードバックにも共通するのですが、こちらの意図は次のような認識でよろしいでしょうか。
- 単一issueの中で課題1、課題2・・・に分ける
- あまりに作業ボリュームが大きい場合、複数issueに分割する
